spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/emiteai
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        # Configurações do Hibernate Envers
        envers:
          audit_table_suffix: _aud
          revision_field_name: rev
          revision_type_field_name: revtype
          store_data_at_delete: true
          default_schema: public
          # Usar nossa entidade de revisão customizada
          revision_entity: com.emiteai.entities.CustomRevisionEntity

  flyway:
    enabled: true
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: false
    clean-disabled: false
    locations: classpath:db/migration

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/emiteai
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        # Configurações do Hibernate Envers
        envers:
          audit_table_suffix: _aud
          revision_field_name: rev
          revision_type_field_name: revtype
          store_data_at_delete: true
          default_schema: public
          # Usar nossa entidade de revisão customizada
          revision_entity: com.emiteai.entities.CustomRevisionEntity

  flyway:
    enabled: true
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: false
    clean-disabled: false
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configurações específicas para desenvolvimento
management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: "*"
        allowed-headers: "*"

---
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/emiteai
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        # Configurações do Hibernate Envers
        envers:
          audit_table_suffix: _aud
          revision_field_name: rev
          revision_type_field_name: revtype
          store_data_at_delete: true
          default_schema: public
          # Usar nossa entidade de revisão customizada
          revision_entity: com.emiteai.entities.CustomRevisionEntity

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    
logging:
  level:
    org.flywaydb: DEBUG
    com.emiteai: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework.boot.sql.init: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.tool.hbm2ddl: DEBUG

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

# Configurações específicas para Docker
management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"
        allowed-methods: "*"
        allowed-headers: "*"
