# 🔧 CONFIGURAÇÕES ADICIONAIS PARA HIBERNATE ENVERS
# Adicione estas configurações ao seu application.yml

spring:
  jpa:
    properties:
      hibernate:
        envers:
          # Configurações adicionais (adicione às existentes)
          audit_strategy: org.hibernate.envers.strategy.DefaultAuditStrategy
          audit_strategy_validity_end_rev_field_name: revend
          audit_strategy_validity_store_revend_timestamp: true
          # Configurações de performance
          use_revision_entity_with_native_id: true
          track_entities_changed_in_revision: true
